Repository wecode-bootcamp-korea/39-2nd-CGW-frontend, pull requests merged in 2022-12, with the labels that each got.

#3 [39기 이다빈] ADD: Book A layout 구축 완료 & 컨플릭트 완료 ✅
  package-lock.json
  package.json
  public/images/insideOut.jpg
  src/Router.js
  src/pages/Book/BookA.js
  src/pages/Book/BookARsv.js
Labels: 멘토 리뷰 요청

#2 [39기 박지영] 메인페이지 movie list layout rebase 완료
  .gitignore
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#1 [39기 박지영] login 및 추가정보요청 페이지 리뷰 반영
  .gitignore
  package-lock.json
  package.json
  public/images/kakao.png
  public/images/naver.png
  public/images/paper.jpg
  public/images/popcorn.png
  public/images/popcornbig.png
  public/images/texture.jpg
  public/images/texture2.jpg
  public/images/ticket.png
  public/images/ticket1280.png
  public/index.html
  src/Router.js
  src/pages/Login/KakaoLogin.js
  src/pages/Login/KakaoOauth.js
  src/pages/Login/Login.js
  src/pages/Login/NaverLogin.js
  src/pages/Login/NaverOauth.js
  src/pages/Login/UserInfo.js
Labels: 멘토 리뷰 요청

#7 [39기 곽종범] ADD: BOOK-B 레이아웃 완료
  package-lock.json
  public/data/seat.json
  public/images/siba.jpg
  src/Router.js
  src/pages/Book/BookB.js
Labels: 멘토 리뷰 요청

#11 [39기 박지영] footer 구현완료
  package-lock.json
  package.json
  public/images/flogin.png
  public/images/fmovie.png
  public/images/forder.png
  public/images/fpopcorn.png
  public/images/ticketmini.png
  src/components/Footer/Footer.js
Labels: 멘토 리뷰 요청

#8 [39기 박지영] moviemain conflict 해결, 리뷰반영
  .gitignore
  package-lock.json
  package.json
  src/pages/Main/Main.js
Labels: 완료

#12 [39기 박지영] 예매내역 페이지 내 지도 안내
  package-lock.json
  package.json
  public/images/minipopcorn.png
  public/images/popcorn2.png
  src/pages/Payment/Map.js
  src/pages/Payment/Payment.js
  src/pages/Payment/placeData.js
Labels: 멘토 리뷰 요청

#6 [39기 이다빈] ADD: Book A 기능구현 중
  package-lock.json
  public/data/movieData.json
  public/data/moviePlaceData.json
  public/data/movieTimeData.json
  src/Router.js
  src/pages/Book/Book.js
  src/pages/Book/BookA.js
  src/pages/Book/BookARsv.js
  src/pages/Book/BookB.js
Labels: 멘토 리뷰 요청

#10 [39기 곽종범] ADD: 좌석선택 기능구현중
  .vscode/seat.json
  package-lock.json
  package.json
  public/data/reservedSeat.json
  src/pages/Book/BookB.js
Labels: 멘토 리뷰 요청

#5 [39기 이혜원] payment 페이지 레이아웃 구현완료
  package-lock.json
  public/data/reservationData.json
  public/images/check.png
  src/Router.js
  src/pages/Payment/Payment.js
  src/pages/Payment/PaymentKakao.js
  src/pages/Payment/component/Modal.js
Labels: Rebase 요청
